### ISSUE TITLE
Remove mbed reference from https://github.com/ARMmbed/greentea/

### ISSUE THREAD

**Issue by rwalton-arm** [ARMmbed/greentea#314]

**Comment by Patater** [comment]
Fixed by https://github.com/ARMmbed/greentea/pull/302/commits/49197c62fc41c4782b229e98cc3cf93cf603b90c

We still have references to "Mbed Enabled" platforms, because the tool has some functionality that doesn't yet work with non-Mbed-Enabled platforms and that's the most straightforward way of documenting support.
